### ISSUE TITLE
Off Topic - Show & Tell

### ISSUE THREAD

**Issue by viper33802** [hellresistor/FIFU-Project#2]
I like what you are doing here. You seems more organized than my garden automation. My code is all over the place. I am not sure if you have a discord or any platform to chat about your project but I would be interested to talk to others doing similar automation as me to see how you fixed issues or found solutions. I would also love to show off what I have created as well. Let me know if you have any interest in something like that?

Here are a few of my dashboards I have setup. They are designed for and look best on mobile.
![2021-03-04_10-20-28](https://user-images.githubusercontent.com/845244/110010678-6a66d580-7cd3-11eb-98a9-55cf284ca6e4.png)

**Comment by hellresistor** [comment]
Hi! @viper33802 
Of corse Yes! I have Discord. 
add hellresistor#4589

You have a BOSSY Dashboard! 🥇

**Comment by hellresistor** [comment]
correction of discord ID ;)
